---

#check systems are debian (ubuntu) and update the systems first

 - name: Fail if not running on Debian
   fail: msg="These tasks should only be run on Debian/Ubuntu servers"
   when: ansible_os_family != "Debian"

 - name: update and upgrade packages via apt
   apt:
    upgrade=yes
    update_cache=yes
